### ISSUE TITLE
"bpftune is not supported"

### ISSUE THREAD

**Issue by srcshelton** [oracle/bpftune#37]
I'm trying to run `bpftune` from a `--privileged` container (rootful, via podman) on kernel 6.3.6 with the following configuration:

```
$ zgrep BPF /proc/config.gz 
CONFIG_BPF=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_ARCH_WANT_DEFAULT_BPF_JIT=y
# BPF subsystem
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT=y
CONFIG_BPF_JIT_ALWAYS_ON=y
CONFIG_BPF_JIT_DEFAULT_ON=y
CONFIG_BPF_UNPRIV_DEFAULT_OFF=y
CONFIG_BPF_PRELOAD=y
CONFIG_BPF_PRELOAD_UMD=m
# end of BPF subsystem
CONFIG_CGROUP_BPF=y
CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_BPFILTER=y
# CONFIG_BPFILTER_UMH is not set
CONFIG_NET_CLS_BPF=m
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_STREAM_PARSER=y
CONFIG_LWTUNNEL_BPF=y
# HID-BPF support
# end of HID-BPF support
```

… and after building from commit 9c99014b7febb0d4724288006cec4695ef858efa I get the following:

```
/ # bpftune -d -S
bpftune: set caps (count 1)
bpftune: set caps (count 2)
bpftune: drop caps (count 1)
bpftune: set caps (count 2)
bpftune: libbpf: loading object 'probe_bpf' from buffer
bpftune: libbpf: elf: section(3) fentry/setup_net, size 16, link 0, flags 6, type=1
bpftune: libbpf: sec 'fentry/setup_net': found program 'entry__setup_net' at insn offset 0 (0 bytes), code size 2 insns (16 bytes)
bpftune: libbpf: elf: section(4) iter/tcp, size 128, link 0, flags 6, type=1
bpftune: libbpf: sec 'iter/tcp': found program 'probe_cong_iter' at insn offset 0 (0 bytes), code size 16 insns (128 bytes)
bpftune: libbpf: elf: section(5) tp_btf/neigh_create, size 16, link 0, flags 6, type=1
bpftune: libbpf: sec 'tp_btf/neigh_create': found program 'bpftune_neigh_create' at insn offset 0 (0 bytes), code size 2 insns (16 bytes)
bpftune: libbpf: elf: section(6) cgroup/sysctl, size 16, link 0, flags 6, type=1
bpftune: libbpf: sec 'cgroup/sysctl': found program 'sysctl_write' at insn offset 0 (0 bytes), code size 2 insns (16 bytes)
bpftune: libbpf: elf: section(7) license, size 7, link 0, flags 3, type=1
bpftune: libbpf: license of probe_bpf is GPL v2
bpftune: libbpf: elf: section(8) .bss, size 25, link 0, flags 3, type=8
bpftune: libbpf: elf: section(9) .maps, size 112, link 0, flags 3, type=1
bpftune: libbpf: elf: section(20) .BTF, size 2281, link 0, flags 0, type=1
bpftune: libbpf: elf: section(22) .BTF.ext, size 324, link 0, flags 0, type=1
bpftune: libbpf: elf: section(30) .symtab, size 720, link 1, flags 0, type=2
bpftune: libbpf: looking for externs among 30 symbols...
bpftune: libbpf: collected 0 externs total
bpftune: libbpf: map 'ring_buffer_map': at sec_idx 9, offset 0.
bpftune: libbpf: map 'ring_buffer_map': found type = 27.
bpftune: libbpf: map 'ring_buffer_map': found max_entries = 131072.
bpftune: libbpf: map 'netns_map': at sec_idx 9, offset 16.
bpftune: libbpf: map 'netns_map': found type = 1.
bpftune: libbpf: map 'netns_map': found key [12], sz = 8.
bpftune: libbpf: map 'netns_map': found value [12], sz = 8.
bpftune: libbpf: map 'netns_map': found max_entries = 65536.
bpftune: libbpf: map 'last_event_map': at sec_idx 9, offset 48.
bpftune: libbpf: map 'last_event_map': found type = 1.
bpftune: libbpf: map 'last_event_map': found key [12], sz = 8.
bpftune: libbpf: map 'last_event_map': found value [12], sz = 8.
bpftune: libbpf: map 'last_event_map': found max_entries = 65536.
bpftune: libbpf: map 'probe_hash_map': at sec_idx 9, offset 80.
bpftune: libbpf: map 'probe_hash_map': found type = 1.
bpftune: libbpf: map 'probe_hash_map': found key [12], sz = 8.
bpftune: libbpf: map 'probe_hash_map': found value [12], sz = 8.
bpftune: libbpf: map 'probe_hash_map': found max_entries = 65536.
bpftune: libbpf: map 'probe_bp.bss' (global data): at sec_idx 8, offset 0, flags 400.
bpftune: libbpf: map 4 is "probe_bp.bss"
bpftune: libbpf: failed to find valid kernel BTF
bpftune: libbpf: Error loading vmlinux BTF: -3
bpftune: libbpf: failed to load object 'probe_bpf'
bpftune: libbpf: failed to load BPF skeleton 'probe_bpf': -3
bpftune: full bpftune support not available: Unknown error -3
bpftune: libbpf: loading object 'probe_bpf_legacy' from buffer
bpftune: libbpf: elf: section(3) kprobe/setup_net, size 16, link 0, flags 6, type=1
bpftune: libbpf: sec 'kprobe/setup_net': found program 'entry__setup_net' at insn offset 0 (0 bytes), code size 2 insns (16 bytes)
bpftune: libbpf: elf: section(4) raw_tracepoint/neigh_create, size 16, link 0, flags 6, type=1
bpftune: libbpf: sec 'raw_tracepoint/neigh_create': found program 'bpftune_neigh_create' at insn offset 0 (0 bytes), code size 2 insns (16 bytes)
bpftune: libbpf: elf: section(5) cgroup/sysctl, size 16, link 0, flags 6, type=1
bpftune: libbpf: sec 'cgroup/sysctl': found program 'sysctl_write' at insn offset 0 (0 bytes), code size 2 insns (16 bytes)
bpftune: libbpf: elf: section(6) license, size 7, link 0, flags 3, type=1
bpftune: libbpf: license of probe_bpf_legacy is GPL v2
bpftune: libbpf: elf: section(7) .bss, size 25, link 0, flags 3, type=8
bpftune: libbpf: elf: section(8) .maps, size 112, link 0, flags 3, type=1
bpftune: libbpf: elf: section(18) .BTF, size 2117, link 0, flags 0, type=1
bpftune: libbpf: elf: section(20) .BTF.ext, size 160, link 0, flags 0, type=1
bpftune: libbpf: elf: section(28) .symtab, size 624, link 1, flags 0, type=2
bpftune: libbpf: looking for externs among 26 symbols...
bpftune: libbpf: collected 0 externs total
bpftune: libbpf: map 'ring_buffer_map': at sec_idx 8, offset 0.
bpftune: libbpf: map 'ring_buffer_map': found type = 27.
bpftune: libbpf: map 'ring_buffer_map': found max_entries = 131072.
bpftune: libbpf: map 'netns_map': at sec_idx 8, offset 16.
bpftune: libbpf: map 'netns_map': found type = 1.
bpftune: libbpf: map 'netns_map': found key [12], sz = 8.
bpftune: libbpf: map 'netns_map': found value [12], sz = 8.
bpftune: libbpf: map 'netns_map': found max_entries = 65536.
bpftune: libbpf: map 'last_event_map': at sec_idx 8, offset 48.
bpftune: libbpf: map 'last_event_map': found type = 1.
bpftune: libbpf: map 'last_event_map': found key [12], sz = 8.
bpftune: libbpf: map 'last_event_map': found value [12], sz = 8.
bpftune: libbpf: map 'last_event_map': found max_entries = 65536.
bpftune: libbpf: map 'probe_hash_map': at sec_idx 8, offset 80.
bpftune: libbpf: map 'probe_hash_map': found type = 1.
bpftune: libbpf: map 'probe_hash_map': found key [12], sz = 8.
bpftune: libbpf: map 'probe_hash_map': found value [12], sz = 8.
bpftune: libbpf: map 'probe_hash_map': found max_entries = 65536.
bpftune: libbpf: map 'probe_bp.bss' (global data): at sec_idx 7, offset 0, flags 400.
bpftune: libbpf: map 4 is "probe_bp.bss"
bpftune: libbpf: map 'ring_buffer_map': created successfully, fd=5
bpftune: libbpf: map 'netns_map': created successfully, fd=6
bpftune: libbpf: map 'last_event_map': created successfully, fd=7
bpftune: libbpf: map 'probe_hash_map': created successfully, fd=8
bpftune: libbpf: map 'probe_bp.bss': created successfully, fd=9
bpftune: libbpf: prog 'entry__setup_net': BPF program load failed: Invalid argument
bpftune: libbpf: prog 'entry__setup_net': failed to load: -22
bpftune: libbpf: failed to load object 'probe_bpf_legacy'
bpftune: libbpf: failed to load BPF skeleton 'probe_bpf_legacy': -22
bpftune: legacy bpftune support not available (load): Unknown error -22
bpftune: drop caps (count 1)
bpftune: bpftune is not supported
bpftune: bpftune is not supported on this system; exiting
```

With:

```
$ cat /proc/sys/kernel/unprivileged_bpf_disabled
0
```

The problem appears to be:

```
bpftune: libbpf: failed to find valid kernel BTF
bpftune: libbpf: Error loading vmlinux BTF: -3
```

… but what can cause this?

**Comment by alan-maguire** [comment]
it's looking for vmlinux BTF which is usually available in /sys/kernel/btf/vmlinux. BTF for kernel/modules is made available here via in-kernel mechanisms. does your container have a way to make /sys/kernel/btf available?

**Comment by srcshelton** [comment]
The host outside the container doesn't have this either 😲

`/sys/kernel` contains no `btf` directory (I assume that this should be available via `sysfs` and doesn't need another mount overlaid?)… I wonder what module/kernel-configuration setting I'm missing?

**Comment by alan-maguire** [comment]
Is CONFIG_DEBUG_INFO_BTF specified? That's needed to get /sys/kernel/btf/vmlinux

**Comment by srcshelton** [comment]
Sorry for the delay here - I've only just come back to this issue…

I've looked at my kernel configuration, and to enable `CONFIG_DEBUG_INFO_BTF` requires several efficiency-sapping debug options to be enabled as well: so long as I have the `vmlinux` file from the kernel build, can this be used to allow `bpftune` to operate _without_ enabling the various `CONFIG_DEBUG_*` options - or are the debug options mandatory to provide `bpftune` with the access it needs?

**Comment by alan-maguire** [comment]
> Sorry for the delay here - I've only just come back to this issue…
> 
> I've looked at my kernel configuration, and to enable `CONFIG_DEBUG_INFO_BTF` requires several efficiency-sapping debug options to be enabled as well: so long as I have the `vmlinux` file from the kernel build, can this be used to allow `bpftune` to operate _without_ enabling the various `CONFIG_DEBUG_*` options - or are the debug options mandatory to provide `bpftune` with the access it needs?

BPF Type Format (BTF) is needed for attaching higher-performance BPF programs such as "fentry/fexit" (kernel function entry/exit) and "tp_btf" (tracepoints). It's possible to force bpftune legacy mode via the "-L" option - this means you use slower kprobes instead of fentry, etc. I haven't tested it without BTF as most distros ship with BTF these days, but you could give that a try.

I'm curious about which debug options are causing you pain - the aim is to make BTF tenable for as many systems as possible (including embedded),  so any feedback on what is problematic is useful. If the problem is DWARF debug info, note that most distros strip it out of the vmlinux image and deliver it via a separate debuginfo package - BTF is generated via DWARF, but once generated it doesn't need it to hang around in the kernel image.

This usually happens as part of the packaging process however, so if you're building kernels manually you might not get this benefit. I belatedly discovered "make INSTAL_MOD_STRIP=1 modules_install install" which does the job for a hand-built kernel, maybe that might help.

Or maybe the issue is something else?

**Comment by srcshelton** [comment]
> BPF Type Format (BTF) is needed for attaching higher-performance BPF programs such as "fentry/fexit" (kernel function entry/exit) and "tp_btf" (tracepoints). It's possible to force bpftune legacy mode via the "-L" option - this means you use slower kprobes instead of fentry, etc. I haven't tested it without BTF as most distros ship with BTF these days, but you could give that a try.

Ah, interesting, thanks - I'll give that a try!  I guess this requires `CONFIG_KPROBES`… any other kernel options you're aware of?

Do you anticipate that bpftune might itself be materially affected by using the slower mechanism, or are even slower kprobes more than fast enough for this tool's usage patterns?

> I'm curious about which debug options are causing you pain - the aim is to make BTF tenable for as many systems as possible (including embedded), so any feedback on what is problematic is useful. If the problem is DWARF debug info, note that most distros strip it out of the vmlinux image and deliver it via a separate debuginfo package - BTF is generated via DWARF, but once generated it doesn't need it to hang around in the kernel image.

The greatest problem I found is that somewhat memory-constrained systems (and we're talking 4GB, so not actually that small) would OOM when trying to link a kernel with debug enabled.

Recently , the BPF options required `CONFIG_DEBUG_INFO_DWARF4`, but as-of (IIRC) 6.4.x, `CONFIG_DEBUG_INFO_DWARF5` can also be used, and this reports 15-18% savings in image and debug-info sizes.

`CONFIG_DEBUG_INFO_REDUCED` cannot be selected, but I believe this only has a build-time impact.  `CONFIG_DEBUG_INFO_SPLIT` likewise can't be selected - but this may also be built-time only with `INSTALL_MOD_STRIP` set.

> This usually happens as part of the packaging process however, so if you're building kernels manually you might not get this benefit. I belatedly discovered "sudo make INSTALL_MOD_STRIP=1 modules_install install" which does the job for a hand-built kernel, maybe that might help.

Yeah, I roll my own kernels and some of the hardware targets are systems that by today's standards would likely be considered 'embedded' (including hosts used as routers, various flavours of Raspberry Pi, etc.)

I've recently updated my container-based build-system to use `INSTALL_MOD_STRIP=1`, so hopefully that'll mitigate (some of?) the impact.

I'll admit that I don't fully understand whether enabling the kernel DEBUG options discussed here solely adds additional strippable sections to the resulting kernel binaries, or whether they also add additional code-paths which may impact performance - in case of the latter, is there any way to get libbpf/bpftune to use a `vmlinux` file created during a kernel-build without DEBUG enabled, as I see that (as previously mentioned) the file `/boot/vmlinux-$(uname -r)` is also referenced by `Makefile` when looking for Type Info.  I did try adding this file, but it didn't seem to make a difference (or, at least, enough of a difference for `bpftune` to report that the system is supported).

(I ask these questions mostly in the hope that they might be useful for writing "An Idiots' Guide to Getting Started with bpftune" at some point in the future! 😅)

**Comment by srcshelton** [comment]
(Argh, I typed a lengthy reply to this and GitHub lost it when the page refreshed 😩)

> BPF Type Format (BTF) is needed for attaching higher-performance BPF programs such as "fentry/fexit" (kernel function entry/exit) and "tp_btf" (tracepoints). It's possible to force bpftune legacy mode via the "-L" option - this means you use slower kprobes instead of fentry, etc. I haven't tested it without BTF as most distros ship with BTF these days, but you could give that a try.

Ah, good to know - I'll try to test this.  I guess `CONFIG_KPROBES` is required… any other kernel options, do you know?

> I'm curious about which debug options are causing you pain - the aim is to make BTF tenable for as many systems as possible (including embedded), so any feedback on what is problematic is useful. If the problem is DWARF debug info, note that most distros strip it out of the vmlinux image and deliver it via a separate debuginfo package - BTF is generated via DWARF, but once generated it doesn't need it to hang around in the kernel image.

I've just done a recompile, and with the only change being setting `CONFIG_DEBUG_INFO_DWARF5`, `CONFIG_DEBUG_INFO_COMPRESSED_ZLIB` and `CONFIG_DEBUG_INFO_BTF`, the compressed kernel size increases from 6.8MB to 7.6MB (~12%) and the modules directory (with `INSTALL_MOD_STRIP=1`) from 38MB to 43MB (~13%) - no not huge gains in the scheme of things, but it shows that even with stripped modules there's clearly additional content present in the kernel and its modules due to having enabled these debug options.

The main issue, however, is that it takes significantly more memory to compile with the updated configuration - whereas the kernel without debug options can compile comfortably on a 4GB system (and possibly even a 1GB system!), I had to increase the memory allocated to my container-based build system to over 8GB (12GB worked, I didn't try to bisect the difference) in order for linking `vmlinux.o` not to OOM.

Therefore, if there were a means to use a `/boot/vmlinux-$(name -r)` (or similar) file without kernel debug options enabled to find the BPF Type Info (… or a means to build a debug-enabled kernel, extract the necessary file(s), and then rebuild without the debug options but re-use the saved data?) then this would be incredibly handy for what are now likely considered embedded systems (e.g. quad-core ~1GHz 4GB routers, Raspberry Pi hosts, etc.)

**Comment by alan-maguire** [comment]
thanks for collecting this data, it's great to know! the problem is that using the current scheme, DWARF is required to generate BTF, and the process of going from DWARF->BTF is very compute-intensive and takes a large amount of memory. I suspect the memory utilization peaks during the execution of "pahole" to generate BTF data. I'll mention your experience to the pahole maintainer; there may be ways to ensure compilation still works (albeit more slowly); 4GB should be enough to build the kernel.

I'm interested in the increased sizes you observe in kernel/modules; a useful comparison might be to "objdump -h  vmlinux" (i.e. the uncompressed kernel) in both cases to see if additional ELF sections are still present after stripping that are not there for the non-DWARF case.

Returning to bpftune itself, I did some experiments with a kernel with no BTF, and "bpftune -S" correctly identifies that legacy mode should be used, but the tuners still fail to load. I'm looking for the root cause of that currently..

**Comment by alan-maguire** [comment]
I've spent a fair bit of time getting bpftune to run without BTF, and I'm still hitting some walls. Even if we could get this to work, the key problem is we lose the benefit of Compile Once - Run Everywhere (CO-RE) that comes with BTF and that introduces risk that BPF programs that were built on kernel X will fail on kernel Y as the data structure offsets are different. I've pursued the approach of replacing use of BPF_CORE_READ() with BPF_PROBE_READ() - the latter of which is the non-CO-RE variant, but oddly I'm still seeing CO-RE relocations, and hence the program doesn't load without BTF (since CO-RE usage mandates BTF). So I suggest for now we 

- leave this issue open as "run bpftune without BTF" and try to figure out remaining issues with running without BTF
- explore the issues you've described to lower the barriers to BTF adoption

Will probably be a week or two till I can work on this again due to other commitments, but hopefully we can figure it out.

**Comment by srcshelton** [comment]
This is the `KPROBES`-based solution?  I'll rebuild and test this ASAP, thanks!

**Comment by alan-maguire** [comment]
we ran into multiple ID issues with pahole v1.24, but these should mostly have been resolved with pahole v1.25. Can you do a few things if you get a chance
- attach your kernel .config
- provide the version of LLVM, pahole used
If you are using pahole v1.24 or earlier, and you're in a position to pull the latest version from https://github.com/acmel/dwarves and build it, that would be great.

we've got a few reports of issues like this but haven't been able to reproduce them yet unfortunately. thanks!

**Comment by srcshelton** [comment]
```
$ sudo podman run -it --rm --entrypoint /bin/sh 0c153301ba95 
/ # pahole --version
v1.25
/ # /usr/lib/llvm/14/bin/clang --version
clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm/14/bin
```

(LLVM is at v14 due to kernel rust dependencies)

[config.txt](https://github.com/oracle/bpftune/files/12440469/config.txt)

**Comment by srcshelton** [comment]
Update on this: `linux-6.5` supports a more recent version of rust, and so I've been able to update the build-dependencies and rebuild the kernel with `clang-16`.

I still get lots of warning output very similar to the above from `pahole`, though: the `unreachable instruction` and all of the `relocation to !ENDBR` still seem to be present, but the `tag not supported` and `multiple IDs found` lines have now disappeared.

**Comment by alan-maguire** [comment]
thanks for the update! I wasn't able to reproduce the issue with multiple ids using your config, but the cause of that in the past has been issues with the algorithm used to remove duplicate data structures (termed BTF de-duplication). if you get a chance, check if bpftune works on a BTF-less system; it does for me, but would be good to confirm that part of the problem is solved on your side too. thanks again!

**Comment by alan-maguire** [comment]
given that the issues reported here result from a mismatch between BTF support in libbpf used to build bpftune and the kernel BTF (something outside of bpftune's control), closing this one out..
